provider:
  type: file
  # Future HTTP provider example:
  # type: http
  # config:
  #   url: "https://api.example.com/auth"
  #   cache_ttl: 300
  #   timeout: 10

# Users allowed to use sudo (passwordless sudo access)
sudoers:
  - admin
  - miguel

users:
  miguel:
    uid: 2000
    gid: 2000
    gecos: "Miguel Campos"
    dir: "/home/miguel"
    shell: "/bin/bash"
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7vKuIl8X2wXIvGx1Qr... miguel@example.com"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI8H1E5qhL9X2wXIvGx1Q... miguel@laptop"

  alice:
    uid: 2001
    gid: 2001
    gecos: "Alice Smith"
    dir: "/home/alice"
    shell: "/bin/bash"
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMz9K1qL3x4vWfZ8w... alice@desktop"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGx1Qr7vKuIl8X2wXIv... alice@mobile"

  bob:
    uid: 2002
    gid: 2002
    gecos: "Bob Johnson"
    dir: "/home/bob"
    shell: "/bin/zsh"
    keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKuIl8X2wXIvGx1Qr7v... bob@server"

  admin:
    uid: 1000
    gid: 1000
    gecos: "System Administrator"
    dir: "/root"
    shell: "/bin/bash"
    keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDx4vWfZ8wSMz9K1qL... admin@management"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIl8X2wXIvGx1Qr7vKu... admin@backup"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1qL3x4vWfZ8wSMz9... admin@emergency"

groups:
  miguel:
    gid: 2000
    members:
      - miguel

  alice:
    gid: 2001
    members:
      - alice

  bob:
    gid: 2002
    members:
      - bob

  admin:
    gid: 1000
    members:
      - admin

  developers:
    gid: 3000
    members:
      - alice
      - bob

  sudo:
    gid: 27
    members:
      - admin
      - miguel
