provider:
  type: http
  environment: "prod-us-west" # Environment ID for registration (required)
  config:
    url: "https://api.p0.app/portal"
    cache_ttl: 60 # Cache timeout in seconds (default: 300) - handled by CacheProvider wrapper
    timeout: 10 # HTTP request timeout in seconds (default: 10)
  # HTTP API Endpoints expected by the provider:
  # POST {url}/user          - Get user by username
  # POST {url}/user_by_uid   - Get user by UID
  # POST {url}/group         - Get group by groupname
  # POST {url}/group_by_gid  - Get group by GID
  # POST {url}/keys          - Get SSH keys for user
  # POST {url}/users         - List all users
  # POST {url}/groups        - List all groups
  # POST {url}/checksudo     - Check if user has sudo access
  # POST {url}/initgroups    - Get supplementary groups for user
  # POST {url}/register      - Register new machine (used by CLI)
  #
  # All requests include machine fingerprint, public key, environment ID, and timestamp:
  # {"fingerprint": "SHA256:abc123...", "public_key": "ssh-ed25519 AAAAC3Nza...", "environment_id": "prod-us-west", "timestamp": 1234567890, ...params}
  #
  # All endpoints receive environment_id automatically from the provider configuration.
  # Registration endpoint example:
  # {"fingerprint": "SHA256:abc123...", "public_key": "ssh-ed25519 AAAAC3...", 
  #  "timestamp": 1234567890, "hostname": "web-server-01", "public_ip": "203.0.113.1", 
  #  "environment_id": "prod-us-west", "labels": ["region=us-west", "team=backend"],
  #  "key": "web-server-01,203.0.113.1,SHA256:abc123...,ssh-ed25519 AAAAC3..."}

# Logging verbosity: error, warn, info, debug, trace (default: info)
log_level: info

# Cache settings for NSS cache module (very important for HTTP provider performance)
cache:
  enabled: true # Enable cache population (default: true)
  refresh_interval: 6 # Hours between full cache refresh (more frequent for HTTP)
  on_demand_update: true # Update cache when users accessed via socket

# System users/groups to automatically deny (performance optimization)
deny_users:
  - mail
  - daemon
  - bin
  - sys
  - sync
  - games
  - man
  - lp
  - news
  - uucp
  - proxy
  - www-data
  - backup
  - list
  - irc
  - gnats
  - nobody
  - systemd-network
  - systemd-resolve
  - messagebus
  - systemd-timesync
  - syslog
  - _apt
  - tss
  - uuidd
  - systemd-oom
  - tcpdump
  - avahi-autoipd
  - usbmux
  - dnsmasq
  - kernoops
  - avahi
  - cups-pk-helper
  - rtkit
  - whoopsie
  - sssd
  - speech-dispatcher
  - nm-openvpn
  - saned
  - colord
  - geoclue
  - pulse
  - gdm
  - debian-exim

# System groups to automatically deny (performance optimization)
deny_groups:
  - mail
  - daemon
  - bin
  - sys
  - adm
  - tty
  - disk
  - lp
  - news
  - uucp
  - man
  - proxy
  - kmem
  - dialout
  - fax
  - voice
  - cdrom
  - floppy
  - tape
  - sudo
  - audio
  - dip
  - www-data
  - backup
  - operator
  - list
  - irc
  - src
  - gnats
  - shadow
  - utmp
  - video
  - sasl
  - plugdev
  - staff
  - games
  - users
  - nogroup
  - systemd-journal
  - systemd-network
  - systemd-resolve
  - crontab
  - messagebus
  - systemd-timesync
  - input
  - sgx
  - kvm
  - render
  - syslog
  - _apt
  - tss
  - bluetooth
  - ssl-cert
  - uuidd
  - systemd-oom
  - tcpdump
  - ssh
  - landscape
  - lxd
  - systemd-coredump
  - avahi-autoipd
  - netdev
  - usbmux

# System UIDs to automatically deny (performance optimization)
deny_uids:
  - 1 # daemon
  - 2 # bin
  - 3 # sys
  - 4 # sync
  - 5 # games
  - 6 # man
  - 7 # lp
  - 8 # mail
  - 9 # news
  - 10 # uucp
  - 33 # www-data
  - 34 # backup
  - 65534 # nobody

# System GIDs to automatically deny (performance optimization)
deny_gids:
  - 1 # daemon
  - 2 # bin
  - 3 # sys
  - 4 # adm
  - 5 # tty
  - 6 # disk
  - 7 # lp
  - 8 # mail
  - 9 # news
  - 10 # uucp
  - 33 # www-data
  - 34 # backup
  - 65534 # nogroup

